# Generated by Django 5.0.2 on 2024-03-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_satkarma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Username',
            new_name='username',
        ),
    ]
