# Generated by Django 5.0.2 on 2024-03-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_satkarma', '0002_rename_username_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(),
        ),
    ]
