# Generated by Django 5.0.2 on 2024-03-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_satkarma', '0003_alter_student_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=60)),
                ('MRP', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
    ]
